# Generated by Terraform - do not edit by hand
[nginx_servers]
%{ for name, ip in hosts ~}
${name} ansible_host=${ip}
%{ endfor ~}

[nginx_servers:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=${ssh_key}
ansible_python_interpreter=/usr/bin/python3
